# volume only for mysql database
# backend sometimes need to connect to database

version: "3"
networks: 
  expense: # docker network create expense
volumes:
  mysql: # docker volume create mysql
services:
  mysql:
    image: mlndockerhub/mysql:v1
    container_name: mysql # --name mysql
    volumes: 
    - mysql: /var/lib/mysql # -v mysql:/var/lib/mysql

  backend:
    image: mlndockerhub/backend:v1
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
    - mysql

  frontend:
    image: mlndockerhub/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend
  

